Receive:
  Email:
    - "2892211452@qq.com"

Send:
    Email : "kengerbot@qq.com"
    SMTPPwd : "miuesngqlvvjdcee"
    SMTPServer : "smtp.qq.com"

Template:
  MessageTmp : "æ˜¯{}çš„ç”Ÿæ—¥ğŸ‚ï¼Œå…·ä½“æ—¥æœŸæ˜¯{}ï¼ˆ{}ï¼‰"
  HaveAgeMessageTmp : "æ˜¯{}çš„{}å²ç”Ÿæ—¥ğŸ‚ï¼Œå…·ä½“æ—¥æœŸæ˜¯{}ï¼ˆ{}ï¼‰"