# 脚本机器人的名字
name: 'GitHub Actions  Bot'


# 什么时候执行
on:
  # 当push的时候
  push:

  # 定时， 这里是每天零点零分执行
  schedule:
    - cron: '0 0 * * *'

# 任务
jobs:

  # 第一个任务
  bot:
    runs-on: ubuntu-latest
    # 任务的步骤
    steps:
      - name: 'echo'
        #  env,具体的一个step会用到的环境变量
        env:
          var: hello github
          # run,具体的一个步骤运行的命令或者 action。
        run: |
          echo $var

      - name: 'Checkout codes'
        uses: actions/checkout@v1

      # 设置环境
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      # 安装库
      - name: 'Install lib'
        run: pip install -r ./req

      # 执行脚本
      - name: 'runBash'
        run: bash ./test.sh
